Bookers/config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'top' => 'homes#top'
  get 'books' => 'books#index', as: 'books'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @new_book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.save
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      flash[:notice] = "Book was successfully updated."
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  def create
    @new_book = Book.new(book_params)
    if @new_book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@new_book)
    else
      @books = Book.all
      render :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/views/books/edit.html.erb
<h3>Editing Book</h3>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>

Bookers/app/views/books/index.html.erb
<%= flash[:notice] %>
<h2>Books</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>New Book</h2>
<% if @new_book.errors.any? %>
  <%= @new_book.errors.count %>error prohibited this book from being saved:
  <% @new_book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model: @new_book, url:'/books', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

Bookers/app/views/books/show.html.erb
<%= flash[:notice] %>
<h5>Title</h5>
<p><%= @book.title %></p>
<h5>Body</h5>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path(@books) %>

Bookers/app/views/homes/top.html.erb
<html>
  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p>
  <%= link_to "Start", books_path %>
</p>
  </body>
</html>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>